# Generated by Django 4.2.2 on 2023-07-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
