# Generated by Django 4.2.2 on 2023-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
