# Generated by Django 4.2.2 on 2023-07-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_shippingadress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
    ]
