# Generated by Django 4.2.2 on 2023-07-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_slide_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='category',
            new_name='category_slide',
        ),
    ]
