# Generated by Django 4.2.2 on 2023-07-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_slide_category_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category_slide',
        ),
    ]
