# Generated by Django 4.2.2 on 2023-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_adress_delete_shippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='commune',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
