# Generated by Django 4.2.2 on 2023-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_adress_commune_adress_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='name_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
