# Generated by Django 4.2.2 on 2023-08-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_adress_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='state',
        ),
    ]
