# Generated by Django 4.2.2 on 2023-08-24 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_ordertemp_payment_orderitemtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adress'),
        ),
    ]
