# Generated by Django 4.2.2 on 2023-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
