# Generated by Django 4.2.2 on 2023-11-09 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_imagesproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_desc', models.TextField()),
                ('transaction_no', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=10)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank_code', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
