# Generated by Django 3.1.14 on 2023-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_product_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_number',
            field=models.IntegerField(default=0),
        ),
    ]
