# Generated by Django 3.1.14 on 2023-12-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20231215_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_new',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
