# Generated by Django 3.1.14 on 2023-12-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_product_product_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_new',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
