# Generated by Django 5.0 on 2024-01-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_chapter_customer_remove_comment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='story_genre', to='app.genre'),
        ),
    ]
