# Generated by Django 5.0 on 2024-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_chapter_view_alter_story_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
