# Generated by Django 5.0 on 2024-01-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_story_author_story_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
