# Generated by Django 5.0 on 2024-01-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
