# Generated by Django 5.0 on 2024-01-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_delete_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
