# Generated by Django 5.0 on 2024-01-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_delete_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
