# Generated by Django 5.0 on 2024-01-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_story_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
    ]
